site_name: Viktor Senderov
site_description: The Homepage of Viktor Senderov
site_url: https://vsenderov.github.io/

theme:
    name: 'material'
    icon:
        logo: material/library
    font:
        text: Ubuntu
        code: Ubuntu Mono
    language: en
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - search.suggest
        - search.highlight

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - git-revision-date-localized
    - inline-select-svg
    - callouts
    - awesome-nav
    - ezlinks:
        warn_ambiguities: true
        wikilinks: true
        reference_links: false
    - redirects:
        redirect_maps:
          'index.md': 'About/About Viktor Senderov.md'


extra_css:
  - callouts.css
